# Generated by Django 4.2.6 on 2023-10-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_moments_image_alter_profiles_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(blank=True, default='image/avatars/default.jpg', null=True, upload_to='avatars'),
        ),
    ]
