# Generated by Django 4.2.6 on 2023-12-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_tags_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='nickname',
        ),
    ]
