# Generated by Django 4.2.6 on 2023-12-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_profiles_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(blank=True, default='idefault.jpg', null=True, upload_to='avatars'),
        ),
    ]
