# Generated by Django 4.2.6 on 2023-10-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moments',
            name='image',
            field=models.ImageField(upload_to='moments'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(blank=True, default='image/base.jpg', null=True, upload_to='avatars'),
        ),
    ]
