# Generated by Django 4.2.6 on 2023-10-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profiles_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='moment',
        ),
        migrations.AddField(
            model_name='moments',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='app.tags'),
        ),
    ]
