# Generated by Django 4.2.6 on 2023-11-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_tags_moment_moments_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
