# Generated by Django 4.2.6 on 2023-11-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comments_is_delete_likescomment_is_delete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='is_delete',
        ),
    ]
